#!/bin/bash

# remove all from that belong to survey and feature  request

deletedFeatures=("Surveys" "FeatureRequests" "Survey")
for feature in "${deletedFeatures[@]}"; do
  echo "$feature"
rm -f  ../src/modules/"$feature".ts
rm -f ../test/mocks/mock"$feature".ts
gsed -i "s/import..*$feature';//g"  ../src/index.ts
gsed -i "s/$feature,//g"  ../src/index.ts

done
npx eslint  ../src/index.ts --fix
